### ISSUE TITLE
SlideConfig Bug

### ISSUE THREAD

**Issue by rezo-evodion** [Ks89/angular-modal-gallery#156] opened 2018-08-17 11:12 UTC
## I'm submitting a...

<pre><code>
[*] Bug report  
[* ] Feature request

I do not know if it is a Bug or Feature Request but I am sure you can find it out,
</code></pre>

## Current behavior

Use [slideConfig]="{infinite: true, sidePreviews: {show: false}}, I can see the next and Previous Image Buttons when there is only one Image in Gallery.

## Expected behavior

Next and Previous Button in case one Image in Gallery are hidden, 

## What is the motivation / use case for changing the behavior?

Hide the Button when they don't have any functionality.

## Environment (the most important section to fill very carefully)

<pre><code>
- Node version: v8.11.3  
- npm version: 5.6.0  
- Operating System and version:  < Windows 10>
- Angular version: 6.1 
- angular-cli version (or SystemJS/Webpack):  6.0.8 
- I'm using Server Side Rendering with angular-universal: YES
- I'm compiling with mode: DEBUG 

Browser:
- [*] Chrome (desktop) version 68.0.3440.106
- [* ] Firefox version 61.0.2

**Comment by Ks89** [comment] 2018-08-17 12:58
you are right. This issue is caused by 'infinite: true' with only one image. I'll fix it.

Do you need a quick fix? Or can I add it directly to version 7.0.0?

**Comment by rezo-evodion** [comment] 2018-08-17 13:03
when you can provide a quick fix, it will be great because it should be done next monday.
Thanks for quick response.

**Comment by Ks89** [comment] 2018-08-17 19:33
6.2.1 released with a fix. Feel free to re-open if you find this issue again

**Closed by Ks89** 2018-08-17 19:33 UTC
Labels: comp:client, comp:testing, effort1:easy (hours), priority:high, type:bug
