### ISSUE TITLE
overlay issue in material template

### ISSUE THREAD

**Issue by momopaper** [Ks89/angular-modal-gallery#137] opened 2018-04-16 11:26 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
</code></pre>

## Current behavior

I am having an overlay issue over here, i think picture speak faster and clearer

![1](https://user-images.githubusercontent.com/6683119/38806014-87b00c68-41aa-11e8-8f91-669c74a75fdb.jpeg)

as you can see, the side bar and top navigation bar overlapping the backdrop and image, the close button even hiding behind the top nav bar

## Expected behavior

![2](https://user-images.githubusercontent.com/6683119/38806191-02a76e98-41ab-11e8-84aa-d08379de05a1.jpeg)

This result is exactly what I expected.

## Environment (the most important section to fill very carefully)

<pre><code>
- Node version: X.X.X  
- npm version: X.X.X  
- Operating System and version:  
- Angular version: X.Y.Z 
- angular-cli version (or SystemJS/Webpack): X.Y.Z 
- I'm using Server Side Rendering with angular-universal: YES/NO
- I'm compiling with mode: DEBUG / PROD / PROD with AOT

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

</code></pre>

**Comment by Ks89** [comment] 2018-04-16 18:48
Hi, that is happening because probably material is using a very high z-index.
Do you have a minimal working example on github or a plunkr/stackblitz live demo?

**Comment by Ks89** [comment] 2018-04-18 20:33
Ok, I removed node_modules, now it's working.

This issue is not easy to fix, because the problem isn't z-index. However, It's similar to #95.
Modal gallery is built to fill the entire viewport. In your situation, part of the viewport contains sidebars.

I need to investigate to find a different approach. I cannot promise a quick solution, because I have to release a new major release to do this.

**Comment by momopaper** [comment] 2018-04-23 08:48
thanks for the help and sorry for no reply as i was not around my pc recently >< , yup i was trying to mess with z-index but no luck, it is ok to take your time :D

**Comment by Ks89** [comment] 2018-04-23 09:13
Yes z-index is not enough. It's more complicated.

**Comment by fenderjair** [comment] 2018-07-03 21:10
@momopaper were you able to fix this issue ? I'm facing it the same problem in my project.

**Comment by Ks89** [comment] 2018-07-04 16:38
Hi.

This is really difficult to fix. Honestly I don't know how, but I'm happy to talk about possibile solutions and ideas. 

Feel free to share proposals to start a discussion

**Comment by gagandeepbal** [comment] 2018-07-24 03:57
Any update on this issue? Facing this same issue.

**Comment by gagandeepbal** [comment] 2018-07-24 04:38
Setting the z-index on sidenav content (where router-outlet is) fixed the issue. Also, i'm switching mode of sidenav based on screen size using flex-layout, so i have to use ngStyle for setting z-index when sidenav mode is set to side.

NOTE: I'm using material sidenav in my app.

**Comment by Ks89** [comment] 2018-07-24 06:14
Thank u, but I'm not able to fix this issue alone.
If you share a runnable example I'll try to investigate again. 
More runnable examples as github repos or on stackblitz you share more easily I'll fix this issue. 

I'm not using material in production, so it's not simple to simulate all scenarios.

**Comment by momopaper** [comment] 2018-07-24 06:16
too bad, i cant find the solution, me and my friends did try fix but unfortunately

**Comment by Ks89** [comment] 2018-07-24 16:52
Do you have runnable examples with angular material on github to show issues with materie?

**Comment by Ks89** [comment] 2018-09-01 19:52
I'm experimenting cdk and it's interesting. When I'm ready to integrate into the library I'll update this issue.

**Comment by Ks89** [comment] 2019-01-21 23:57
@veliksergey I'll fix this with 8.0.0 (already work in progress), but I have to re-write a big part of the library (only internal stuff), so I need some time to do that.

First of all, I'll release 7.3.0 next month with a huge internal change to speed up 8.0.0 release. In this way, I can add the required changes that I'm experimenting on top of 7.3.0.

**Comment by veliksergey** [comment] 2019-01-22 23:04
@Ks89 I was able to go around this problem by putting ks-modal-gallery inside inside mat-dialog component
Of course it's not the best solution, but it should work for now

Main Component: 

`<figure *ngFor="let img of images">
    <img [src]="img.modal.img" [alt]="product.title" (click)="openGalleryDialog(img)">
  </figure>`

`openGalleryDialog(image: Image) {
    const index = image ? this.images.indexOf(image) : -1;
    this.dialog.open(GalleryDialogComponent, {
      data: {
        images: this.images,
        galleryConfig: this.galleryRowDescConfig,
        index: index
      }
    });
  }`


In GalleryDialogComponent:

`constructor(
    public dialogRef: MatDialogRef<GalleryDialogComponent>,
    @Inject(MAT_DIALOG_DATA) public data: {
      images: Image[],
      galleryConfig: PlainGalleryConfig,
      index: number
  }
  ) { }

  ngOnInit() {
    setTimeout(() => {
      this.data.galleryConfig = Object.assign(
        {}, this.data.galleryConfig, {
          layout: new AdvancedLayout(this.data.index, true)
        }
      );
    }, 0);
  }

  closeDialog(): void {
    this.dialogRef.close();
  }`

`<ks-modal-gallery [id]="1"
                  (close)="closeDialog()"
                  [modalImages]="data.images"
                  [plainGalleryConfig]="data.galleryConfig">
</ks-modal-gallery>


<button mat-raised-button
        color="accent"
        mat-dialog-close>
  Close Me
</button>
`

**Comment by veliksergey** [comment] 2019-01-22 23:16
@Ks89  I was able to go around this problem by putting ks-modal-gallery inside mat-dialog component
Of course it's not the best solution, but it should work for now

Main Component: 
```
galleryRowDescConfig: PlainGalleryConfig = {
    strategy: PlainGalleryStrategy.CUSTOM,
    layout: new AdvancedLayout(-1, true)
  };

constructor(private dialog: MatDialog) { }

openGalleryDialog(image: Image) {
    const index = image ? this.images.indexOf(image) : -1;
    this.dialog.open(GalleryDialogComponent, {
      data: {
        images: this.images,
        galleryConfig: this.galleryRowDescConfig,
        index: index
      }
    });
  }
```

```
<figure *ngFor="let img of images">
    <img [src]="img.modal.img" [alt]="product.title" (click)="openGalleryDialog(img)">
  </figure>
```


In GalleryDialogComponent:

```
constructor(
    public dialogRef: MatDialogRef<GalleryDialogComponent>,
    @Inject(MAT_DIALOG_DATA) public data: {
      images: Image[],
      galleryConfig: PlainGalleryConfig,
      index: number
  }
  ) { }

  ngOnInit() {
    setTimeout(() => {
      this.data.galleryConfig = Object.assign(
        {}, this.data.galleryConfig, {
          layout: new AdvancedLayout(this.data.index, true)
        }
      );
    }, 0);
  }

  closeDialog(): void {
    this.dialogRef.close();
  }
```

```
<ks-modal-gallery [id]="1"
                  (close)="closeDialog()"
                  [modalImages]="data.images"
                  [plainGalleryConfig]="data.galleryConfig">
</ks-modal-gallery>

<!-- close btn in case dialog won't close -->
<button mat-raised-button
        color="accent"
        mat-dialog-close>
  Close Me
</button>
```

**Comment by Ks89** [comment] 2020-04-11 20:38
Fully implemented (branch `800`) with angular/cdk and scheduled for 8.0.0-beta.1 that is coming soon.

I close this issue because already done and It will be available in a beta release in some days.

**Closed by Ks89** 2020-04-11 20:38 UTC
Labels: breaking changes, comp:client, comp:testing, effort3:hard (weeks), priority:high, type:feature
