### ISSUE TITLE
Can't get the gallery to work!!

### ISSUE THREAD

**Issue by NathofGod** [Ks89/angular-modal-gallery#139] opened 2018-05-01 16:32 UTC
I've been using this library for over a year now. After upgrading everything broke and now I'm struggling to get the gallery to display correctly with the default settings. It looks nothing like the demo and I've done nothing but put it in

<img width="973" alt="image" src="https://user-images.githubusercontent.com/1936466/39482105-a4e5f39e-4d65-11e8-93ce-20f3c4bdee79.png">

**Comment by Ks89** [comment] 2018-05-01 16:55
Hi, I'm sorry for the problems, but please, fill the issue template with versions and so on.
Otherwise, It's impossibile to help you.

Which version of the library are you using (try to remove node modules and package-lock and reinstall all your deps again)? 
Which angular angular-cli version? 
Do you have a runnable example to reproduce this issue?

PS what does it mean "after upgrading"? From which version and to which version?

**Comment by Ks89** [comment] 2018-05-21 17:07
Is this still an issue?
If yes please write more information to be able to help you, if not, please close it.

**Comment by Ks89** [comment] 2018-05-27 16:08
Close because without feedbacks

**Closed by Ks89** 2018-05-27 16:08 UTC
Labels: need investigation, need more information
