### ISSUE TITLE
Download Images in new Tab

### ISSUE THREAD

**Issue by rezo-evodion** [Ks89/angular-modal-gallery#138] opened 2018-04-19 15:14 UTC
Hi,
First of all thank you, because you saved a lot of time and effort for me.
I implemented the gallery in my Html:

<ks-modal-gallery [modalImages]="getModalImages()"
                    [downloadable]="true"
                    [buttonsConfig]="ButtonsConfigSimple"
                    [plainGalleryConfig]="customPlainGalleryColumnConfig">
  </ks-modal-gallery>

 customPlainGalleryColumnConfig: PlainGalleryConfig = {
    strategy: PlainGalleryStrategy.CUSTOM,
    layout: new AdvancedLayout(-1, true)
  };

  buttonsConfigSimple: ButtonsConfig = {
    visible: true,
    strategy: ButtonsStrategy.SIMPLE,
  };

and works perfectly except the download, it does not make it into a new Tap but in the Tap where my app is(same Tap).
any Ideas?

**Comment by Ks89** [comment] 2018-04-19 18:51
@rezo-evodion check the official demo for this feature here https://ks89.github.io/angular-modal-gallery-2018.github.io/demo/buttons-exturl-newtab

**Comment by Ks89** [comment] 2018-04-19 18:53
Hi, what does it mean "tap"? Are you talking about browser's tabs.

Please fill the template with all versions, browsers and so on. I cannot help without all information.

**Comment by rezo-evodion** [comment] 2018-04-23 07:18
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[x] Support request
</code></pre>

## Current behavior

I created a component and I provided an array of image and I set the Downloadable to true 

 <ks-modal-gallery [modalImages]="getModalImages()"
                    [downloadable]="true"
                    [buttonsConfig]="getButtonsConfigSimple()"
                    [plainGalleryConfig]="getCustomPlainGalleryColumnConfig()">
  </ks-modal-gallery>

but when I click on download button it downloads in the same Browser Tab.

## Expected behavior

open the Image in new Browser Tab


## Environment (the most important section to fill very carefully)

<pre><code>
- Node version: v9.2.0  
- npm version: 5.6.0  
- Operating System and version:Windows  
- Angular version:  5.2.3 
- angular-cli version (or SystemJS/Webpack): 1.6.5 
- I'm using Server Side Rendering with angular-universal: YES
- I'm compiling with mode: DEBUG 



Browser:
- [x] Chrome (desktop) version  65.0.3325.181 
- [x] Firefox version 59.0.2

**Comment by Ks89** [comment] 2018-04-27 18:42
Sorry for the delay, but I was really busy.

Yes, if you click 'download' it automatically download the image. This library won't navigate to the image, but it downloads the image automatically.
So I don't understand why It should open the image in another tab, since it is capable to download it directly without navigating to it.

Please could you explain what are you trying to achieve? Because "open the Image in new Browser Tab" could be a bug, but also a feature request.

If is it a bug, I'll fix it, however I have a runnable example to reproduce it, because I'm not able to re-create it.

**Comment by rezo-evodion** [comment] 2018-05-03 07:43
Sorry also for the delay.
when I click on Download button in your demo it opens the image in new Browser Tap, so I do not know if this is a bug or a Feature?
when I implement the Gallery in our Project and click on Download Button it redirects the page to image Url.

**Comment by Ks89** [comment] 2018-05-21 17:08
Hi @rezo-evodion, are you using images from an external server and not from your assets folder?

**Comment by rezo-evodion** [comment] 2018-05-24 07:51
Hello, 
yes, I am providing the image list from Server and not from assets folder.

**Comment by Ks89** [comment] 2018-05-24 08:22
Ok I'll try next week, please be patient because this week I'm really busy.

**Comment by Ks89** [comment] 2018-05-27 16:39
Ok, I confirm the issue, however, as explained in #140 it's a new browser's restriction introduced in Spring 2018 (look here https://stackoverflow.com/a/17527821 and also here https://developers.google.com/web/updates/2018/02/chrome-65-deprecations#block_cross-origin_wzxhzdk5a_download) and probably I can't do anything to fix it.

You should move your images inside your server.

I tried with different browsers and it's working on Opera, but on Chrome, Safari and so on, there is that restriction.

What can I do? I don't know, I'll try to search an alternative to download images automatically, however I think that I'll update the doc website adding a disclaimer to explain this browser's limitation.

I close the issue, because this is not something really related to the library, however, if you want you can continue this discussion here #140 also with the user "Enngage".

**Closed by Ks89** 2018-05-27 16:39 UTC
Labels: help wanted, need more information, question, waiting
