### ISSUE TITLE
Cannot find name 'ExtendedKeyboardEvent'.

### ISSUE THREAD

**Issue by efirvida** [Ks89/angular-modal-gallery#104] opened 2017-11-18 02:27 UTC
Hi, I'm having this error when building my project.

`ERROR in node_modules/angular-modal-gallery/services/keyboard.service.d.ts(15,21): error TS2304: Cannot find name 'ExtendedKeyboardEvent'.`

My system configurations is:
-> Angular 5
-> node 8.9.1
 and I installed this component via npm so I think that is the last version.

I made My own fixe by changing:
`add(onBind: (e: ExtendedKeyboardEvent, combo: string) => any): void;` 
to
`add(onBind: (e, combo: string) => any): void;`

But I thinks its not the solution.

**Comment by Ks89** [comment] 2017-11-18 16:36
Hi, 
I have some questions:
- which versions on angular-modal-gallery?
- did you add this `ModalGalleryModule.forRoot()` to your MainModule
- which version of angular-cli are you using?
- did you try to remove `package-lock.json` file and `node_modules` folder and reinstall everything with `npm install`?

**Comment by Ks89** [comment] 2017-11-18 16:39
Also, do you have a minimal demo on github to reproduce this issue?

**Comment by efirvida** [comment] 2017-11-19 13:05
-> My angular-cli is 1.5
-> My  angular-modal-gallery is 4.0.1
-> In the main mmodule I use like this: `ModalGalleryModule.forRoot( { shortcuts: ['ctrl+a', 'ctrl+s', 'meta+s'] } )` as the documentation say
-> yes  I reinstall all my modules

can't make a simple minimal demo  i'm building a wordpress theme

by I can put my code here:

**my component:**

```

import {Component, OnInit} from '@angular/core';
import {PageService} from '../../../services/pages.service';
import {ContentFormatService} from '../../../services/content.format.service';
import {AppOptionService} from '../../../services/options.service';
import {Post} from '../../../models/post';
import {Image} from 'angular-modal-gallery';
import {ImageModalEvent} from 'angular-modal-gallery/components/modal-gallery.component';

@Component({
  selector: 'app-inspire',
  templateUrl: './inspire.component.html',
  styleUrls: ['./inspire.component.scss'],
  providers: [PageService, AppOptionService, ContentFormatService]
})
export class InspireComponent implements OnInit {

  public isLoading = true;
  public page = new Post();
  public imagesArray = [];
  openModalWindow: boolean = false;
  imagePointer: number = 0;


  constructor(private pageService: PageService,
              private formatContent: ContentFormatService,
              private appOptions: AppOptionService) {
  }

  ngOnInit() {
    this.pageService.getPage('14').subscribe(
      (page => {
        this.page = this.formatContent.formatContent(page);
        this.appOptions.getSettings('inspirepage').subscribe(
          (opts => {
            this.isLoading = false;
            this.page.options = opts;
            this.page.options.gallery.forEach(element => { //format my image data to use i in the gallery 
              this.imagesArray.push({
                img: element.full,
                thumb: element.medium
              })
            });
          }),
          (err => {
            console.log({
              error: err
            });
            this.isLoading = false;
          })
        );
      }),
      (err => console.log({
        error: err
      })),
    );
  }

  openImageModal(image: Image) {
    this.imagePointer = this.imagesArray.indexOf(image);
    this.openModalWindow = true;
  }

  onCloseImageModal(event: ImageModalEvent) {
    this.openModalWindow = false;
  }

}
```
**my view:**

```
      <div class="masonry-grid">
        <div class="masonry-grid-item" *ngFor="let img of imagesArray; let i = index">
          <img [src]="img.thumb" (click)="openImageModal(img)">
        </div>
      </div>

      <div *ngIf="openModalWindow">
        <modal-gallery [modalImages]="imagesArray"
                       [imagePointer]="imagePointer"
                       (close)="onCloseImageModal($event)"></modal-gallery>
      </div>
```

**Comment by Ks89** [comment] 2017-11-19 16:33
Hi!
I tried to use `ModalGalleryModule.forRoot( { shortcuts: ['ctrl+a', 'ctrl+s', 'meta+s'] } )` with angular-cli 1.5 and it's working.
Please check this example https://github.com/Ks89/angular-modal-gallery/tree/master/demo/angular-cli and try to run it by yourself to see if it is working or not. If yes, try to compare your project with my official angular-cli demo.

I never saw this issue, so without a runnable example I cannot provide the best support. Also, I never used wordpress.

**Comment by Ks89** [comment] 2017-11-23 00:38
Hi @efirvida are there any news about this issue?
Did you find the solution or it is still an issue? If it is still a problem, did you try to use my demo project  https://github.com/Ks89/angular-modal-gallery/tree/master/demo/angular-cli ?

**Comment by vugar005** [comment] 2017-12-06 13:23
@Ks89 
Hi. I also had this issue. Tried your solution but did not help. I edited` 'ExtendedKeyboardEvent`' in keyboard.service.d.ts to `'any' `and problem gone. But wanted you to be aware of that.
```
  "@angular/core": "^4.2.4",
 "@angular/cli": "1.4.5",
   "angular-modal-gallery": "^4.0.1",
```
Tried below solutions but did not help.
1. Removed package-lock.json file and node_modules folder and reinstall everything with npm install
2. Changed to `ModalGalleryModule.forRoot( { shortcuts: ['ctrl+a', 'ctrl+s', 'meta+s'] } )` 
Currently changing to any type solves problem.

**Comment by Ks89** [comment] 2017-12-06 17:40
Hi @vugar005 do you have a runnable example?
I really don't know how to fix it without a minimal demo to reproduce this issue. 

However,  please check this example https://github.com/Ks89/angular-modal-gallery/tree/master/demo/angular-cli and try to run it by yourself to see if it is working or not. If yes, try to compare your project with my official angular-cli demo.

**Comment by Ks89** [comment] 2017-12-06 18:15
Oh wait a minute guys.
Did you install @types/mousetrap in this way: `npm install --save-dev @types/mousetrap` ?

You need both @types/hammerjs and @types/mousetrap.

**Comment by vugar005** [comment] 2017-12-06 18:22
@Ks89 
You are right I did not `install npm i --save-dev @types/hammerjs @types/mousetrap`.
Just installed `npm i --save angular-modal-gallery hammerjs mousetrap`. 
It is probably because of this. Going to add it to project and inform tomorrow.

**Comment by efirvida** [comment] 2017-12-08 18:29
Hi Sorry for my late response, my designers change the web design so no need to use this any more at least on the current site. But I test it again using `npm install --save-dev @types/mousetrap` and it works thanks a lot for the support

**Comment by Ks89** [comment] 2017-12-09 00:20
Ok I close this issue.

if there are other problems, please add a comment here and I'll reopen this issue.

**Closed by Ks89** 2017-12-09 00:20 UTC
Labels: need more information, question

**Comment by bghanchi** [comment] 2018-01-31 13:19
"npm i --save angular-modal-gallery hammerjs mousetrap "work

**Comment by asarapas** [comment] 2018-03-29 12:37
Has same issue. Can confirm, that adding @types/hammerjs @types/mousetrap as devDependencies got rid of error

**Comment by douglazsilva** [comment] 2020-09-26 20:37
i run npm install --save-dev @ types / hammerjs and npm install --save-dev @ types / mousetrap
and in the file "node_modules/@ks89/angular-modal-gallery/lib/services/keyboard.service.d.ts" I added import {ExtendedKeyboardEvent} from 'mousetrap'; and worked

**Comment by Ks89** [comment] 2020-09-27 09:19
Hi @douglazsilva , this issue is very old and related to a very old angular-modal-gallery version.
Which version of the library are you using? Also, which version of angular?

**Comment by douglazsilva** [comment] 2020-09-27 14:37
@Ks89 I use angular 9 and angular-modal-gallery 7.2.5

**Comment by Zuiia** [comment] 2020-09-27 23:44
I am running into the same issue with angular 10.1.2 and modal-gallery 7.2.5

**Comment by Ks89** [comment] 2020-09-28 19:05
Mmm, interesting, I didn't find this issue when I tried 7.x.x with those angular versions, however it seems weird.

I suggest to try version 8.x.x beta. This version should be ok and it's already stable. "beta" is more because I still writing tests and documentation, but I already published a full live demo on stackblitz. For more info check this issue #183 
I want to do some changes to the API but nothing special, only easy stuff to migrate, in particular on carousel component, because I should migrate it to the new libconfig interface.

**Comment by DariusLT** [comment] 2020-09-29 18:01
I tried your version 8.0.0-beta with Angular 7.x.x, but am running into this one:

```shell
ERROR in Maximum call stack size exceeded
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@2.0.0 build: `ng build --prod`
npm ERR! Exit status 1
npm ERR!
```
I did try it with the beta version, cuz I got a weird behaviour with version 7. I opened an issue for that as well:

[https://github.com/Ks89/angular-modal-gallery/issues/212](https://github.com/Ks89/angular-modal-gallery/issues/212)

**Comment by moeneqbal** [comment] 2021-05-07 12:57
i am facing the same issue in react app, i am using yarn for package management, i have added both hammer.js & moustrap.js, any other solution?

My react app, hammer.js, mousetrap, weekly-schedular versions are listed below.

"react": "^17.0.1",
"@types/hammerjs": "2.0.39",
"@types/mousetrap": "1.6.8",
"@remotelock/react-week-scheduler": "^3.5.8",


thanks in advance.
