### ISSUE TITLE
Module parse failes on css

### ISSUE THREAD

**Issue by kadosh1000** [Ks89/angular-modal-gallery#72] opened 2017-07-31 17:36 UTC
Hi, I am using your module with webpack.
I get an error while compiling the components:

![image](https://user-images.githubusercontent.com/2615945/28789892-c8e83eea-762f-11e7-8524-858912f4306a.png)

It seems like the styles urls are targeting the scss files instead of css files causing it to throw an error.
Is there a simple fix for it?

In my opinion the css files should be at least generated on postinstall and the components should be targeting the .css files

**Comment by Ks89** [comment] 2017-08-01 06:37
Hi!
In every starter/skeleton/template that I tested there is always sass-loader.
This library is tested both with systemjs, angular-cli and webpack. Also I created a working example based on the template by AngularClass.

I didn't consider your scenario, but if you want I can test it. To do that, I need a working template to use it as a starting point. For instance, your package.json and all your webpack's config files.

PS: honestly I don't consider this as really important, but if you want I can try to work on it.

Question: why not sass? Is there a real reason?

**Comment by kadosh1000** [comment] 2017-08-01 12:31
My project is using this seed:
https://github.com/qdouble/angular-webpack2-starter

It also uses sass, and I am using it in my project.
The thing is the scss files are precompiled to css and the components are refrencing the css file.
I think this is a better way to support users that don't use sass or users that uses sass but not on runtime compilation (like me).

Currently I cannot use this module because of this problem.

**Comment by Ks89** [comment] 2017-08-01 19:38
@kadosh1000 which branch of https://github.com/qdouble/angular-webpack2-starter are you using? Master branch or another one?

**Comment by kadosh1000** [comment] 2017-08-02 11:18
@Ks89  I have taken the master branch about two months ago,
but i guess it haven't changes too much since, so I think the current master should be just fine.

**Comment by Ks89** [comment] 2017-08-02 21:53
Ok, I'm doing some experiments. I'll update this issue in a couple of days. Please by patient.

**Comment by Ks89** [comment] 2017-08-06 08:47
Hi! I created a fork of angular-webpack2-starter and I applied these modifications https://github.com/Ks89/angular-webpack2-starter-demo-with-angular-modal-gallery/commit/987d52e5dbb5482db54099b9c7f8b4c7829cef3f

It is working (probably not everything, since universal isn't fully supported right now).

PS: I cannot reproduce your bug with the latest version of the starter by qdouble.

Could you retry?

**Comment by Ks89** [comment] 2017-08-22 23:17
@kadosh1000 are there some news? Did you fix the problem?  :)

Can I close this issue? XD

**Comment by kadosh1000** [comment] 2017-08-23 02:17
@Ks89 
Hi unfortunately I was looking for a solution that will include AOT compilation. You can close this issue

**Closed** 2017-08-23 09:03 UTC
